blank_issues_enabled: false  # Desativa a criaÃ§Ã£o de issues em branco

contact_links:
  - name: â“ Perguntas e Suporte
    url: question.md
    about: Use o fÃ³rum de discussÃµes para dÃºvidas gerais e suporte. (Need to configure)
    labels: [question]

issue_templates:
  - name: ğŸ› Bug Report
    path: bug_report.md
    about: Relate um problema encontrado no sistema.
    labels: [bug]

  - name: ğŸš€ Feature Request
    path: feature_request.md
    about: Sugira uma nova funcionalidade ou melhoria.
    labels: [enhancement]
